notifications:
  email:
    recipients:
      - sebastian@jaenicke.org

language: java

dist: bionic

sudo: required

jdk: oraclejdk11

branches:
  only:
    - GPMS_2_0

cache:
  directories:
  - $HOME/.m2

before_install:
  - sudo add-apt-repository -y ppa:maarten-fonville/protobuf
  - sudo apt-get update -qq
  - sudo apt-get install -qq protobuf-compiler
  - git clone -b utilities_2_0 https://github.com/MGX-metagenomics/utilities.git
  - cd utilities && mvn clean install -DskipTests=true && cd .. && rm -rf utilities

script:
  - mvn clean install
