notifications:
  email:
    recipients:
      - sebastian@jaenicke.org

language: java

dist: trusty

sudo: required

jdk: oraclejdk8

branches:
  only:
    - master
    - GPMS_2_0

cache:
  directories:
  - $HOME/.m2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq protobuf-compiler
  - git clone https://github.com/MGX-metagenomics/utilities.git
  - cd utilities && mvn clean install -DskipTests=true && cd .. && rm -rf utilities

script:
  - mvn clean install
