
name: GPMS 1.x CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8 
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Install protoc
      run: sudo apt-get install -qq protobuf-compiler
    - name: Create protoc-3 symlink
      run: sudo ln -s /usr/bin/protoc /usr/bin/protoc-3
    - name: Setup mvn cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-mgx1-cache
    - name: Build 'utilities' 1.x
      run: |
        git clone -b master https://github.com/MGX-metagenomics/utilities.git
        cd utilities
        mvn clean install -DskipTests=true
        cd ..
        rm -rf utilities
    - name: Build with Maven
      run: mvn -B package --file pom.xml
